const arr = ['Pedro', 'João', 'Maicon', 'Davi', 'Eduardo', 'Esau'];
console.log(arr);
delete arr[1];
console.log(arr);
arr[1] = 'Maria';
console.log(arr);
arr.pop();
console.log(arr);
arr.shift();
console.log(arr);
arr.unshift('Cabral');
console.log(arr);
arr.push('Manel');
console.log(arr);
const newArr = arr.slice(2, -2);
console.log(newArr);
const nomes = ['Cicero', 'Junio', 'Santos', 'de', 'Souza'];
console.log(nomes);
const nome = nomes.join(' ');
console.log(nome);
const novoNomes = nome.split(' ');
console.log(novoNomes);